### PR TITLE
Create Incidents

### PR DESCRIPTION
**Pull request by Paul-Eraman-CoopCycle**
new incidents' documentation

### CODE REVIEW

**Comment by vladimir-8** [comment]
@Paul-Eraman-CoopCycle who can/should review it?

**Comment by Paul-Eraman-CoopCycle** [comment]
The documentation?

**Comment by vladimir-8** [comment]
Yes, I mean what blocks this pull request from merging?

**Comment by vladimir-8** [comment]
@Paul-Eraman-CoopCycle I don't know what happened here. It seems these changes have already been added and updated in the `main` branch / https://docs.coopcycle.org/en/ So we don't need to merge this pull request

**Pull request closed without merging**
